FROM existdb/existdb:latest

# Example: Copy a .xar file for deployment
# COPY your_app.xar /exist/autodeploy

# Example: Set the admin password
# RUN java -jar start.jar client --no-gui -u admin -P '' -x "sm:passwd('admin', 'your_password')"

# Example: Copy a custom configuration file
# COPY src/conf.xml /exist/config