services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_front-end
      target: frontend
    volumes:
      - ./search-app/front-end:/app/search-app/front-end
      - /app/search-app/front-end/node_modules
    ports:
      - "5173:5173"
    working_dir: /app/search-app/front-end
    command: sh -c "npm install && npm run dev"

  backend:
    build:
      context: .
      dockerfile: Dockerfile_back-end
      target: backend
    volumes:
      - ./search-app/back-end:/app/search-app/back-end
      - ./search-app/back-end/venv-sar:/app/search-app/back-end/venv-sar
    ports:
      - "8000:8000"
    links:
      - frontend
    working_dir: /app/search-app/back-end
    command: php artisan serve --host=0.0.0.0 --port=8000

  exist:
    build:
      context: .
      dockerfile: Dockerfile_exist
      target: exist
    volumes:
      - ./search-app/exist-data:/app/search-app/exist-data
      - ./search-app/back-end/storage/app/xml-files:/app/search-app/back-end/storage/app/xml-files
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - backend
    links:
      - backend
    working_dir: /app/search-app/exist-data
    command: java -jar start.jar