services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_front-end
    image: sar-repo-frontend:latest
    container_name: sar-repo-frontend
    volumes:
      - ./search-app/front-end:/app/search-app/front-end
      - frontend_node_modules:/app/search-app/front-end/node_modules
    network_mode: "host"  # Use host network mode to make the container accessible via localhost
    working_dir: /app/search-app/front-end
    command: sh -c "npm install && npm run build && npm run preview -- --host 0.0.0.0 --port 5173"
    environment:
      - NODE_ENV=development
      - VITE_APP_URL=https://sar2.andreasmaita.com
      - BACKEND_API_URL=https://sar2.andreasmaita.com/api

  backend:
    build:
      context: .
      dockerfile: Dockerfile_back-end
    image: sar-repo-backend:latest
    container_name: sar-repo-backend
    volumes:
      - ./search-app/back-end:/app/search-app/back-end
      - backend_vendor:/app/search-app/back-end/vendor
      - backend_venv:/opt/venv
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    working_dir: /app/search-app/back-end
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
    
  exist:
      build:
        context: .
        dockerfile: Dockerfile_exist
      image: exist-custom:latest
      container_name: exist-custom
      ports:
        - "8080:8080"
        - "8443:8443"
      command: sh -c "./startup.sh"
      restart: unless-stopped

volumes:
  frontend_node_modules:
    name: sar-repo-frontend-node-modules
  backend_vendor:
    name: sar-repo-backend-vendor
  backend_venv:
    name: sar-repo-backend-venv
  exist-data:
    name: sar-repo-exist-data
  exist-config:
    name: sar-repo-exist-config
  sar-repo-exist-data:
    name: sar-repo-exist-data
  sar-repo-exist-config:
    name: sar-repo-exist-config