name: Run front-end tests

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - working-directory: ./search-app/front-end
      - run: npm ci
      - run: npm run build
      - run: npm run test
